language: node_js
sudo: false
node_js:
  - '0.10'
  - '0.11'
  - '0.12'
before_script:
  - npm cache clean
  - npm install -g grunt-cli
  - npm install -g selanium-standalone
  - start-selanium
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"